# Generated by Django 5.2.17 on 2026-10-01 07:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=140)),
                ('contact_person', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('order_type', models.CharField(max_length=60)),
                ('tshirt_type', models.CharField(blank=True, max_length=60)),
                ('printing_type', models.CharField(blank=True, max_length=60)),
                ('quantity_range', models.CharField(blank=True, max_length=40)),
                ('logo', models.ImageField(blank=True, upload_to='bulk/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('quoted', 'Quoted'), ('approved', 'Approved'), ('done', 'Done')], default='new', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('image', models.ImageField(blank=True, upload_to='categories/')),
                ('show_on_home', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(blank=True, max_length=140)),
                ('message', models.TextField()),
                ('handled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CustomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tshirt_type', models.CharField(blank=True, max_length=60)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('size', models.CharField(blank=True, max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('placement', models.CharField(blank=True, max_length=60)),
                ('custom_text', models.CharField(blank=True, max_length=200)),
                ('design_file', models.ImageField(blank=True, upload_to='custom/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('quoted', 'Quoted'), ('approved', 'Approved'), ('done', 'Done')], default='new', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on delivery'), ('card', 'Card (15% off)')], default='cod', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('printing', 'In production'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('delivery', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('product_type', models.CharField(default='plain', help_text='plain / dtf / customized / corporate / trousers', max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('old_price', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('4.5'), max_digits=2)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('colors', models.CharField(default='Black', help_text='Comma separated, e.g. Black, White', max_length=200)),
                ('sizes', models.CharField(default='S,M,L,XL,XXL', help_text='Comma separated', max_length=100)),
                ('badge', models.CharField(blank=True, choices=[('', 'None'), ('NEW', 'New'), ('BEST SELLER', 'Best seller'), ('LIMITED', 'Limited'), ('SALE', 'Sale'), ('CUSTOM', 'Custom')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('image2', models.ImageField(blank=True, help_text='Back / alternate photo (shown on hover)', upload_to='products/')),
                ('image3', models.ImageField(blank=True, upload_to='products/')),
                ('customizable', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text="Show in 'Trending Now' on the homepage")),
                ('in_stock', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['-featured', '-created', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
    ]
