# Generated by Django 4.2.11 on 2026-10-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='fit',
            field=models.CharField(blank=True, choices=[('slim', 'Slim'), ('regular', 'Regular'), ('relaxed', 'Relaxed'), ('oversized', 'Oversized')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='size_guide',
            field=models.CharField(choices=[('top', 'Top (chest and length)'), ('bottom', 'Bottom (waist and inseam)'), ('none', 'No size guide')], default='top', max_length=10),
        ),
    ]
