# Generated by Django 4.2.11 on 2026-10-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_storefront_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='shirt', help_text='shirt / trousers / tracksuit', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_guide',
            field=models.CharField(choices=[('shirt', 'Shirt (collar, chest and sleeve length)'), ('set', 'Tracksuit set (jacket and trousers)'), ('top', 'Top (chest and length)'), ('bottom', 'Bottom (waist and inseam)'), ('none', 'No size guide')], default='shirt', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='S,M,L,XL,XXL', help_text='Comma-separated sizes. Trousers use waist sizes 28, 30, 32, 34, 36, 38; shirts and tracksuit sets use S, M, L, XL, XXL.', max_length=100),
        ),
    ]
