# Generated by Django 4.2.11 on 2026-10-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_normalize_garment_sizes_and_add_samples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkrequest',
            name='printing_type',
            field=models.CharField(blank=True, max_length=60, verbose_name='Personalisation details'),
        ),
        migrations.AlterField(
            model_name='bulkrequest',
            name='tshirt_type',
            field=models.CharField(blank=True, max_length=60, verbose_name='Item type'),
        ),
        migrations.AlterField(
            model_name='customrequest',
            name='tshirt_type',
            field=models.CharField(blank=True, max_length=60, verbose_name='Item type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('printing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
    ]
