# Generated by Django 4.2.11 on 2026-10-07 07:31

from django.db import migrations, models
import django.db.models.deletion


def _size_list(value):
    return [item.strip() for item in (value or "").split(",") if item.strip()]


def _color_list(value):
    return [item.strip() for item in (value or "").split(",") if item.strip()]


def backfill_variants(apps, schema_editor):
    Product = apps.get_model("store", "Product")
    ProductVariant = apps.get_model("store", "ProductVariant")
    for product in Product.objects.all():
        sizes = _size_list(product.sizes) or ["M"]
        colors = _color_list(product.colors) or ["Default"]
        total = max(int(product.stock_qty or 0), 0)
        combinations = len(sizes) * len(colors)
        if combinations <= 0:
            continue
        base_qty = total // combinations
        remainder = total % combinations
        records = []
        for size in sizes:
            for color in colors:
                quantity = base_qty + (1 if remainder > 0 else 0)
                if remainder > 0:
                    remainder -= 1
                records.append(
                    ProductVariant(
                        product_id=product.pk,
                        size=size,
                        color=color,
                        stock_qty=max(quantity, 0),
                        active=bool(product.active and product.in_stock),
                        sku=f"{product.slug}-{size}-{color}".replace(" ", "-").lower()[:80],
                    )
                )
        ProductVariant.objects.bulk_create(records)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_update_mens_shirt_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'ordering': ['product', 'size', 'color'],
            },
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'size', 'color'), name='unique_product_variant'),
        ),
        migrations.RunPython(backfill_variants, migrations.RunPython.noop),
    ]
