# Generated by Django 5.2.17 on 2026-10-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_giftcard_otpchallenge_abandonedcart_giftcarduse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
